import './jquery-global.js';
import 'bootstrap';
import './cookies.js';
import './loading.js';
import 'popper.js';
import './header.js';
import './series.js';
import './dialog.js';
import './fuzzy_search.js';